FROM node:18-alpine

WORKDIR /app

# Installer dépendances (utiliser cache Docker)
COPY package*.json ./
COPY tsconfig.json ./
COPY vite.config.ts ./
RUN npm install

# Copier le reste du projet
COPY . .

# Exposer le port du serveur Vite
EXPOSE 3000

# Commande de démarrage (hot reload)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

